sudo: enabled
dist: trusty
language: python
python:
  - 3.5

services:
  - postgresql

addons:
  postgresql: "9.6"

env:
  -DEBUG=True

before_install:
  - pip3 install pipenv

install:
  - pipenv install --deploy --system --dev

before_script:
  - psql -U postgres -d template1 -c "CREATE EXTENSION hstore;"
  - psql -U postgres -c "CREATE DATABASE ${DATABASE_NAME};"
  - psql -U postgres -c "CREATE USER ${DATABASE_USER} WITH PASSWORD '${DATABASE_PASS}' CREATEDB;"
  - python3 manage.py migrate

script:
  - python3 manage.py test
  - coverage run --source=rules,core manage.py test

after_success: coveralls
