apiVersion: v1
kind: Service
metadata:
  name: yara-guardian
  labels:
    app: yara-guardian
    tier: API
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 31808
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: yara-guardian
    tier: API
